import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from "@/providers/AOSProvider";
import ToastProvider from "@/providers/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AOSProvider>

        <main className="w-screen h-screen bg-linear-to-br from-slate-950 via-emerald-900 to-slate-950 overflow-hidden relative">

        {children}
        </main>
        </AOSProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
