import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from "@/providers/AOSProvider";
import ToastProvider from "@/providers/ToastProvider";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSProvider>
          <Header />
          <main className="relative box-border min-h-screen bg-linear-to-br from-slate-950 via-slate-900 to-slate-950 overflow-hidden">
            <div className="absolute inset-0 z-0 h-screen w-screen">
              <div className="absolute -top-50 -left-50 w-125 h-125 bg-teal-500/30 rounded-full blur-3xl bottomgradient"></div>
              <div className="absolute -bottom-50 -right-50 w-125 h-125 bg-indigo-500/30 rounded-full blur-3xl topgradient"></div>
            </div>
            {children}
          </main>
        </AOSProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
